services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  gateway-svc:
    image: express-gateway
    volumes:
      - ../gateway-service/config/gateway.config.yml:/var/lib/eg/gateway.config.yml
    ports:
      - 8080:8080

  endpoints-svc:
    image: bsgazineu/endpoints-svc:latest
    build:
      context: ../
      dockerfile: ./endpoints-service/Dockerfile
    ports:
      - 7003:7003
    depends_on:
      - postgres  