services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  gateway-svc:
    image: express-gateway
    volumes:
      - ../gateway-service/config/gateway.config.yml:/var/lib/eg/gateway.config.yml
    ports:
      - 8080:8080

  endpoints-svc:
    image: bsgazineu/endpoints-svc:latest
    build:
      context: ../endpoints-service/
      dockerfile: ./Dockerfile
    ports:
      - 7003:80
    depends_on:
      - postgres

  webhooks-svc:
    image: bsgazineu/webhooks-svc:latest
    build:
      context: ../webhooks-service/
      dockerfile: ./Dockerfile
    ports:
      - 7000:80
      - 50001:50001
    depends_on:
      - postgres
      - rabbitmq