http:
  port: 8080
apiEndpoints:
  endpoints:
    host: '*'
    paths: ['/api/endpoints*', '/api/webhooklogs*', '/api/logs']
    methods: ['POST', 'GET', 'PATCH', 'DELETE']
  webhooks:
    host: '*'
    paths: ['/api/webhooks*', '/api/event-types']
    methods: ['POST', 'GET', 'PATCH', 'DELETE']
  events:
    host: '*'
    paths: ['/api/events-delivery']
    methods: ['POST']
  dead-letter:
    hosts: '*'
    paths: ['/api/dead-letter-queue*']
    methods: ['POST', 'GET', 'DELETE']
serviceEndpoints:
  endpoints-service:
    url: 'http://endpoints-svc/'
  webhooks-service:
    url: 'http://webhooks-svc/'
  events-service:
    url: 'http://events-svc/'
  dead-letter-service:
    url: 'http://dead-letter-queue-svc/'
policies:
  - proxy
pipelines:
  endpoints-pipeline:
    apiEndpoints:
      - endpoints
    policies:
      - proxy:
          - action:
              serviceEndpoint: endpoints-service
              changeOrigin: true
  webhooks-pipeline:
    apiEndpoints:
      - webhooks
    policies:
      - proxy:
          - action:
              serviceEndpoint: webhooks-service
              changeOrigin: true
  events-pipeline:
    apiEndpoints:
      - events
    policies:
      - proxy:
          - action:
              serviceEndpoint: events-service
              changeOrigin: true
  dead-letter-pipeline:
    apiEndpoints:
      - dead-letter
    policies:
      - proxy:
          - action:
              serviceEndpoint: dead-letter-service
              changeOrigin: true