http:
  port: 8080
apiEndpoints:
  endpoints:
    host: '*'
    paths: ['/api/endpoints*', '/api/webhooklogs*']
    methods: ['POST', 'GET', 'PATCH', 'DELETE']
  webhooks:
    host: '*'
    paths: ['/api/webhooks*']
    methods: ['POST', 'GET', 'PATCH', 'DELETE']
serviceEndpoints:
  endpoints-service:
    url: 'http://endpoints-svc/'
  webhooks-service:
    url: 'http://webhooks-svc/'
policies:
  - proxy
pipelines:
  endpoints-pipeline:
    apiEndpoints:
      - endpoints
    policies:
      - proxy:
          - action:
              serviceEndpoint: endpoints-service
              changeOrigin: true
  webhooks-pipeline:
    apiEndpoints:
      - webhooks
    policies:
      - proxy:
          - action:
              serviceEndpoint: webhooks-service
              changeOrigin: true